### ISSUE TITLE
reference to missing item causes a crash

### ISSUE THREAD

**Issue by bear** [nlf/gitenforcer#16]
I'm seeing this for some of the github calls:

2013-09-08_02:57:20.04674 production environment detected
2013-09-08_03:28:13.79040 192.30.252.53 - - [Sun, 08 Sep 2013 03:28:13 GMT] "POST /github/callback HTTP/1.1" 200 2 "-" "GitHub Hookshot bbde025"
2013-09-08_03:28:15.17529
2013-09-08_03:28:15.17597 /home/enforcebot/enforcebot/node_modules/gitenforcer/router.js:148
2013-09-08_03:28:15.17644     var sha = pr.head.sha;
2013-09-08_03:28:15.17660                 ^
2013-09-08_03:28:15.18083 TypeError: Cannot read property 'head' of undefined
2013-09-08_03:28:15.18097     at runMiddleware (/home/enforcebot/enforcebot/node_modules/gitenforcer/router.js:148:17)
2013-09-08_03:28:15.18107     at /home/enforcebot/enforcebot/node_modules/gitenforcer/router.js:43:17
2013-09-08_03:28:15.18117     at Object.proto.sendError (/home/enforcebot/enforcebot/node_modules/gitenforcer/node_modules/github/api/v3.0.0/index.js:32:13)
2013-09-08_03:28:15.18128     at /home/enforcebot/enforcebot/node_modules/gitenforcer/node_modules/github/api/v3.0.0/pullRequests.js:80:29
2013-09-08_03:28:15.18140     at IncomingMessage.<anonymous> (/home/enforcebot/enforcebot/node_modules/gitenforcer/node_modules/github/index.js:681:21)
2013-09-08_03:28:15.18150     at IncomingMessage.EventEmitter.emit (events.js:117:20)
2013-09-08_03:28:15.18162     at _stream_readable.js:910:16
2013-09-08_03:28:15.18172     at process._tickCallback (node.js:415:13)

**Comment by jfeldstein** [comment]
:+1: I am seeing this, as well.
